baseURL = "https://turbohustle.com/"
canonifyURLs = true
disqusShortname = "turbohustle-xyz"
enableRobotsTXT = true
googleAnalytics = "UA-111593067-2"
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
title = "Turbo Hustle"
[author]
name = "Sanjiv Raj"
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 5
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[params]
basecolor = "#FD5401"
categoriesbycount = true
customcss = ["default"]
customjs = ["default"]
description = "Emphasizing the art of motor sports in the way it deserves. Boost your horses to experience the lap of honor"
disable_highlight = true
dynamictitles = true
faviconversion = ""
highlightjscdn = "//cdn.bootcss.com"
highlightjslang = ["r", "yaml", "css"]
highlightjstheme = "github"
highlightjsversion = "9.11.0"
includereadingtime = true
loadfavicon = true
mathjaxcdn = "//cdn.bootcss.com"
mathjaxversion = "2.7.1"
navbartitle = "Turbo Hustle"
og_image = "/img/og.jpg"
rssappearatbottom = false
rssappearattop = true
showsidebarcategories = false
socialappearatbottom = false
socialappearattop = true
socialshare = true
socialshareemail = false
socialsharefacebook = true
socialsharegoogleplus = true
socialsharelinkedin = true
socialsharepinterest = false
socialsharereddit = true
socialsharestumbleupon = false
socialsharetwitter = true
viewmorepostlink = "/blog/"
[params.intro]
about = "An Engineer, with a soft spot ♥️ for Motor sports marking the beginning of expressing himself. Since Motorsports turns out to be an epitome of art its mandatory to honor it."
header = "Turbo Hustle"
paragraph = "Emphasizing the art of motor sports in the way it deserves. Boost your horses to experience the lap of honor"
[params.intro.pic]
alt = "Turbo Hustle"
circle = false
imperfect = false
src = "/img/main/logo.png"
width = "100px"
[params.postamount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
facebook = "sanjiiv.raj.1"
instagram = "_sanjiv_r_"
quora = "Sanjiv-Raj-2"
whatsapp = "+919789804349"
youtube = "channel/UCZkDdXuAVjXjaT2s9hug8Xw"
