---
upload_path: "/static/img/:year:/:month:/"
frontmatter_file_url_template: "/img/:year:/:month:/"
body_file_url_template: "/img/:year:/:month:/"
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
  blog:
    default_front_matter_template: blog
version: 0.38.1
