---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/contact
  label: Contact
  create: all
- path: content/blog
  label: Blog
  create: all
  default_front_matter_template: blog
- path: content/about
  label: About
  create: all
upload_dir: static/img
public_path: "/img"
front_matter_path: "/img"
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: 0.38.1
